/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    speakers: Speaker;
    sponsors: Sponsor;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('ca' | 'es' | 'en' | 'fr')
    | ('ca' | 'es' | 'en' | 'fr')[];
  globals: {
    'site-settings': SiteSetting;
    translations: Translation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
  };
  locale: 'ca' | 'es' | 'en' | 'fr';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  /**
   * Professional title (e.g. "Founder and CEO")
   */
  title: string;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Sponsor website URL
   */
  url?: string | null;
  tier: 'platinum' | 'gold' | 'silver' | 'bronze' | 'collaborator';
  /**
   * Global sponsors appear in the footer on all pages
   */
  isGlobal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  /**
   * URL-friendly slug (e.g. "devfest")
   */
  slug: string;
  year: string;
  date: string;
  status: 'upcoming' | 'past';
  featuredImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  actionButtons?: {
    callForPapersEnabled?: boolean | null;
    callForPapersUrl?: string | null;
    ticketsEnabled?: boolean | null;
    ticketsUrl?: string | null;
  };
  speakers?: (number | Speaker)[] | null;
  eventSponsors?:
    | {
        sponsor: number | Sponsor;
        /**
         * Override the sponsor tier for this event only
         */
        tierOverride?: ('platinum' | 'gold' | 'silver' | 'bronze' | 'collaborator') | null;
        id?: string | null;
      }[]
    | null;
  schedule?: {
    days?:
      | {
          dayDate: string;
          id?: string | null;
        }[]
      | null;
    tracks?:
      | {
          trackName: string;
          id?: string | null;
        }[]
      | null;
    sessions?:
      | {
          sessionTitle?: string | null;
          sessionDescription?: string | null;
          sessionSpeaker?: (number | null) | Speaker;
          /**
           * 0 = first day, 1 = second day, etc.
           */
          dayIndex: number;
          /**
           * 0 = first track, 1 = second track, etc.
           */
          trackIndex: number;
          /**
           * Format: HH:MM
           */
          startTime: string;
          /**
           * Format: HH:MM
           */
          endTime: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tier?: T;
  isGlobal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  year?: T;
  date?: T;
  status?: T;
  featuredImage?: T;
  description?: T;
  actionButtons?:
    | T
    | {
        callForPapersEnabled?: T;
        callForPapersUrl?: T;
        ticketsEnabled?: T;
        ticketsUrl?: T;
      };
  speakers?: T;
  eventSponsors?:
    | T
    | {
        sponsor?: T;
        tierOverride?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        days?:
          | T
          | {
              dayDate?: T;
              id?: T;
            };
        tracks?:
          | T
          | {
              trackName?: T;
              id?: T;
            };
        sessions?:
          | T
          | {
              sessionTitle?: T;
              sessionDescription?: T;
              sessionSpeaker?: T;
              dayIndex?: T;
              trackIndex?: T;
              startTime?: T;
              endTime?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general?: {
    siteName?: string | null;
    siteDescription?: string | null;
    contactEmail?: string | null;
    googleAnalyticsId?: string | null;
  };
  hero?: {
    heroImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    heroPrimaryButtonText?: string | null;
    heroPrimaryButtonUrl?: string | null;
    heroSecondaryButtonText?: string | null;
    heroSecondaryButtonUrl?: string | null;
  };
  about?: {
    aboutText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    aboutImage1?: (number | null) | Media;
    aboutImage2?: (number | null) | Media;
  };
  social?: {
    linkedinUrl?: string | null;
    twitterUrl?: string | null;
    youtubeUrl?: string | null;
    twitchUrl?: string | null;
  };
  sponsorTiers?: {
    tiers?:
      | {
          tierId: 'platinum' | 'gold' | 'silver' | 'bronze' | 'collaborator';
          tierLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  nav?: {
    home?: string | null;
    events?: string | null;
    about?: string | null;
    contact?: string | null;
    faq?: string | null;
  };
  buttons?: {
    callForSpeakers?: string | null;
    register?: string | null;
    callForPapers?: string | null;
    tickets?: string | null;
    learnMore?: string | null;
  };
  home?: {
    saveTheDate?: string | null;
    nextEvent?: string | null;
    aboutTitle?: string | null;
    contactTitle?: string | null;
    contactText?: string | null;
    sponsorsTitle?: string | null;
    followUs?: string | null;
  };
  countdown?: {
    days?: string | null;
    hours?: string | null;
    minutes?: string | null;
    seconds?: string | null;
    untilNextEvent?: string | null;
  };
  event?: {
    upcomingEvent?: string | null;
    pastEvent?: string | null;
    speakers?: string | null;
    schedule?: string | null;
    tracks?: string | null;
    day?: string | null;
    noSpeakers?: string | null;
    noSchedule?: string | null;
    sponsorsTitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        siteDescription?: T;
        contactEmail?: T;
        googleAnalyticsId?: T;
      };
  hero?:
    | T
    | {
        heroImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heroPrimaryButtonText?: T;
        heroPrimaryButtonUrl?: T;
        heroSecondaryButtonText?: T;
        heroSecondaryButtonUrl?: T;
      };
  about?:
    | T
    | {
        aboutText?: T;
        aboutImage1?: T;
        aboutImage2?: T;
      };
  social?:
    | T
    | {
        linkedinUrl?: T;
        twitterUrl?: T;
        youtubeUrl?: T;
        twitchUrl?: T;
      };
  sponsorTiers?:
    | T
    | {
        tiers?:
          | T
          | {
              tierId?: T;
              tierLabel?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        home?: T;
        events?: T;
        about?: T;
        contact?: T;
        faq?: T;
      };
  buttons?:
    | T
    | {
        callForSpeakers?: T;
        register?: T;
        callForPapers?: T;
        tickets?: T;
        learnMore?: T;
      };
  home?:
    | T
    | {
        saveTheDate?: T;
        nextEvent?: T;
        aboutTitle?: T;
        contactTitle?: T;
        contactText?: T;
        sponsorsTitle?: T;
        followUs?: T;
      };
  countdown?:
    | T
    | {
        days?: T;
        hours?: T;
        minutes?: T;
        seconds?: T;
        untilNextEvent?: T;
      };
  event?:
    | T
    | {
        upcomingEvent?: T;
        pastEvent?: T;
        speakers?: T;
        schedule?: T;
        tracks?: T;
        day?: T;
        noSpeakers?: T;
        noSchedule?: T;
        sponsorsTitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}